site_name: fast-ai-course-utilities
repo_url: https://github.com/camstuart/fast-ai-course-utilities
site_url: https://camstuart.github.io/fast-ai-course-utilities
site_description: Some utilities for the course as a package for easier re-use
site_author: Cam Stuart
edit_uri: edit/main/docs/
repo_name: camstuart/fast-ai-course-utilities
copyright: Maintained by <a href="https://camstuart.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/camstuart/fast-ai-course-utilities
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fast-ai-course-utilities

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true